INSERT INTO LEVEL_INFO(LINUM,LILEVEL,LINAME,LIDESC) VALUES (1,1,'최고관리자','사장급');
INSERT INTO LEVEL_INFO(LINUM,LILEVEL,LINAME,LIDESC) VALUES (2,2,'중간관리자','부장급');
INSERT INTO LEVEL_INFO(LINUM,LILEVEL,LINAME,LIDESC) VALUES (3,3,'관리자','과장급');
INSERT INTO LEVEL_INFO(LINUM,LILEVEL,LINAME,LIDESC) VALUES (4,4,'정회원','대리급');
INSERT INTO LEVEL_INFO(LINUM,LILEVEL,LINAME,LIDESC) VALUES (5,5,'준회원','사원급');
INSERT INTO LEVEL_INFO(LINUM,LILEVEL,LINAME,LIDESC) VALUES (6,46,'7676','8787');
COMMIT;