INSERT INTO MUSIC_CHART(MCNUM,MCNAME,MCSINGER,MCVENDOR,MCLIKE,MCDISLIKE,MCCREDAT,MCDESC) VALUES (1,'Way Back Home','숀 SHAUN','해피로봇 레코드',199106,2862,'칵스','take');
INSERT INTO MUSIC_CHART(MCNUM,MCNAME,MCSINGER,MCVENDOR,MCLIKE,MCDISLIKE,MCCREDAT,MCDESC) VALUES (2,'Dance the Night Away','TWICE 트와이스','(주)JYP엔터테인먼트',117958,3284,'JYP Nation','Summer Nights');
INSERT INTO MUSIC_CHART(MCNUM,MCNAME,MCSINGER,MCVENDOR,MCLIKE,MCDISLIKE,MCCREDAT,MCDESC) VALUES (3,'뚜두뚜두(DDU-DU DDU-DU)','BLACKPINK','(주)YG엔터테인먼트',184685,7336,'SQUARE ONE','SQUARE UP');
COMMIT;